int wordCount(char* str);
int charCount(char* str);
void vowelConsonantCount(char* str,int& vowels, int& consonants);
void reverseString(char* str);
bool isPalindrome(char* str); 
void toUpperCase(char* str);
void toLowerCase(char* str);
int counterSubstringOccurrence(char* str, char* substr);
void encryptStr(char* plaintext, char* key, char* encryptedStr);
void decryptStr(char* decryptedstr, char* key, char* encryptedStr);
